
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish
      run: |
        cd Csharp_Angular_Typescript/02\ -\ Challenge/Resolved/back
        dotnet publish -c Release -o out

    - name: Build Docker image
      run: |
        cd Csharp_Angular_Typescript/02\ -\ Challenge/Resolved/back
        docker build -t challenge_back_csharp_image .

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build
      run: |
        cd Csharp_Angular_Typescript/02\ -\ Challenge/Resolved/front
        npm install
        npm run build --prod

    - name: Build Docker image
      run: |
        cd Csharp_Angular_Typescript/02\ -\ Challenge/Resolved/front
        docker build -t challenge_front_csharp_image .